name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Visual Studio 2022 Build Tools
        uses: microsoft/setup-msbuild@v2

      - name: Configure project
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build --config Release
